#!/bin/bash
read -p 'Lower limit (0.0-360.0): ' lowerlim
read -p 'Upper limit (0.0-360.0): ' upperlim

gawk -v up="$upperlim" -v lo="$lowerlim" '{if (($5>=lo) && ($5<=up)) print $0}' fluo.dat > tmp.dat
gnuplot <<- EOF
set termoption enhanced
#set title '{/Symbol g}'
set title font ", 20"
#set xlabel 'f'
set xlabel 'FSC'
set xlabel font ", 18"
set xtics font ", 11"
set ylabel font ", 18"
set ytics font ", 11"
#set ylabel '{/Symbol d}' enhanced
set ylabel 'SSC' enhanced
set nokey
set cbrange [0:360]
set palette defined ( 0 '#ff0000',\
	                      1 '#ff7d00',\
                              2 '#ffff00',\
                              3 '#00ff00',\
                              4 '#00ffff',\
	                      5 '#0000ff',\
                              6 '#ff00ff',\
                              7 '#440044')
set term postscript eps enhanced color
set output "result_filter.eps"
plot [0:65533][0:65533] "tmp.dat" using 2:4:5 with points palette pt 7 ps 0.3
# pause mouse "Click on figure using mouse button\n"
# pause  -1 
EOF
